# Generated by Django 3.0.3 on 2020-02-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='a_factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='a factor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='b_factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='b factor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='c_factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='c factor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='d_factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='d factor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='e_factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='e factor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ffs_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ffs type'),
        ),
    ]
