# Generated by Django 2.2.10 on 2020-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dignosis',
            fields=[
                ('qn', models.AutoField(primary_key=True, serialize=False, verbose_name='質問番号')),
                ('factor', models.CharField(max_length=5, verbose_name='因子')),
                ('sentence', models.CharField(max_length=250, verbose_name='質問文')),
            ],
        ),
    ]
