# Generated by Django 2.2.10 on 2020-03-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dof', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dignosis',
            new_name='diagnosis',
        ),
    ]
