# Generated by Django 2.2.10 on 2020-03-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dof', '0002_auto_20200316_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffs_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='91タイプ')),
                ('strength', models.TextField(verbose_name='強み')),
                ('stressor', models.TextField(verbose_name='ストレス要因')),
                ('weakness', models.TextField(verbose_name='弱み')),
                ('advice', models.TextField(verbose_name='アドバイス')),
            ],
        ),
    ]
